# Generated by Django 3.1.1 on 2020-10-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0003_auto_20201005_1113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="authors",
            field=models.ManyToManyField(blank=True, to="papers.Author"),
        ),
        migrations.AlterField(
            model_name="papertranslation",
            name="language_code",
            field=models.CharField(
                choices=[("de", "German"), ("fr", "French"), ("it", "Italian")],
                max_length=7,
                verbose_name="language code",
            ),
        ),
        migrations.AlterField(
            model_name="papertranslation",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translation_set",
                to="papers.paper",
                verbose_name="paper",
            ),
        ),
    ]
