# Generated by Django 3.1.1 on 2020-10-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0005_auto_20201021_1137"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Amendmended",
            new_name="Amendmend",
        ),
    ]
