# Generated by Django 3.1.1 on 2020-11-11 09:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0006_auto_20201021_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papertranslation",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="content"),
        ),
    ]
