# Generated by Django 3.1.1 on 2020-11-23 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("papers", "0008_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="name",
        ),
        migrations.AddField(
            model_name="author",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
