# Generated by Django 3.1.1 on 2020-11-23 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0010_auto_20201123_1232"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="papers.author",
                verbose_name="author",
            ),
        ),
    ]
