# Generated by Django 3.1.1 on 2020-11-24 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("papers", "0011_auto_20201123_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="amendmend",
            name="supporters",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        )
    ]
