# Generated by Django 3.1.1 on 2020-11-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0012_amendmend_supporters"),
        ("papers", "0012_auto_20201124_1332"),
    ]

    operations = []
