# Generated by Django 3.1.1 on 2020-11-24 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("papers", "0012_amendmend_supporters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amendmend",
            name="content",
            field=models.TextField(verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="amendmend",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="body"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="likes"
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="authors",
            field=models.ManyToManyField(
                blank=True, to="papers.Author", verbose_name="authors"
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="working_title",
            field=models.CharField(max_length=255, verbose_name="working title"),
        ),
    ]
