# Generated by Django 3.1.1 on 2020-11-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0013_merge_20201125_0814")]

    operations = [
        migrations.AddField(
            model_name="amendmend",
            name="start_index",
            field=models.IntegerField(default=0, verbose_name="start index"),
        )
    ]
