# Generated by Django 3.1.1 on 2020-11-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0013_auto_20201124_1544")]

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        )
    ]
