# Generated by Django 3.1.1 on 2020-11-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("papers", "0014_amendmend_start_index")]

    operations = [
        migrations.AlterModelOptions(
            name="amendmend", options={"ordering": ["start_index"]}
        )
    ]
