# Generated by Django 3.1.1 on 2020-11-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0015_auto_20201125_0955")]

    operations = [
        migrations.AddField(
            model_name="amendmend",
            name="end_index",
            field=models.IntegerField(default=0, verbose_name="last index"),
        )
    ]
