# Generated by Django 3.1.1 on 2020-11-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0015_auto_20201125_0857")]

    operations = [
        migrations.RenameField(model_name="tag", old_name="word", new_name="name"),
        migrations.AlterField(
            model_name="amendmend",
            name="tags",
            field=models.ManyToManyField(related_name="tag", to="papers.Tag"),
        ),
    ]
