# Generated by Django 3.1.1 on 2020-11-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0017_auto_20201125_1248"),
        ("papers", "0016_auto_20201125_0904"),
    ]

    operations = []
