# Generated by Django 3.1.1 on 2020-11-26 12:02

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("papers", "0018_merge_20201125_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer*in",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="Inhalt"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Likes"
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="amendment_deadline",
            field=models.DateTimeField(verbose_name="Antragsfrist"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="authors",
            field=models.ManyToManyField(
                blank=True, to="papers.Author", verbose_name="Autor*innen"
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="working_title",
            field=models.CharField(max_length=255, verbose_name="Working title"),
        ),
        migrations.RenameModel("Amendmend", "Amendment"),
        migrations.AlterField(
            model_name="comment",
            name="amendment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="papers.amendment",
                verbose_name="Antrag",
            ),
        ),
    ]
