# Generated by Django 3.1.1 on 2020-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0019_auto_20201126_1202")]

    operations = [
        migrations.AlterField(
            model_name="amendment",
            name="content",
            field=models.TextField(verbose_name="Inhalt"),
        ),
        migrations.AlterField(
            model_name="amendment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
    ]
