# Generated by Django 3.1.1 on 2020-12-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0020_auto_20201126_1204")]

    operations = [
        migrations.AlterModelOptions(
            name="amendment",
            options={
                "ordering": ["start_index"],
                "verbose_name": "Antrag",
                "verbose_name_plural": "Anträge",
            },
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Autor*in", "verbose_name_plural": "Autor*innen"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Kommentar", "verbose_name_plural": "comments"},
        ),
        migrations.AlterModelOptions(
            name="paper",
            options={"verbose_name": "Papier", "verbose_name_plural": "Papiere"},
        ),
        migrations.AlterModelOptions(
            name="papertranslation",
            options={
                "verbose_name": "paper translation",
                "verbose_name_plural": "paper translations",
            },
        ),
        migrations.AddField(
            model_name="amendment",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
