# Generated by Django 3.1.1 on 2020-12-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0021_auto_20201202_1657"),
        ("papers", "0021_auto_20201209_1003"),
    ]

    operations = []
