# Generated by Django 3.1.1 on 2021-02-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0022_merge_20201216_0915")]

    operations = [
        migrations.AlterField(
            model_name="amendment",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("public", "Published"),
                    ("final", "Finalized"),
                    ("retracted", "Retracted"),
                ],
                max_length=9,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("public", "Published"),
                    ("final", "Finalized"),
                    ("retracted", "Retracted"),
                ],
                max_length=20,
                verbose_name="state",
            ),
        ),
    ]
