# Generated by Django 3.1.1 on 2020-12-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0022_merge_20201216_0915")]

    operations = [
        migrations.AlterField(
            model_name="amendment",
            name="state",
            field=models.CharField(
                choices=[
                    (
                        "draft",
                        '<u title="ⓘ This paper is a private draft and not ready for amendments.">Draft</u>',
                    ),
                    (
                        "public",
                        '<u title="ⓘ This paper is public and ready for amendments.">Published</u>',
                    ),
                    (
                        "final",
                        '<u title="ⓘ This paper is final no more changes can be made.">Finalized</u>',
                    ),
                ],
                max_length=7,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="state",
            field=models.CharField(
                choices=[
                    (
                        "draft",
                        '<u title="ⓘ This paper is a private draft and not ready for amendments.">Draft</u>',
                    ),
                    (
                        "public",
                        '<u title="ⓘ This paper is public and ready for amendments.">Published</u>',
                    ),
                    (
                        "final",
                        '<u title="ⓘ This paper is final no more changes can be made.">Finalized</u>',
                    ),
                ],
                max_length=20,
                verbose_name="state",
            ),
        ),
    ]
