# Generated by Django 3.1.1 on 2021-02-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0023_auto_20210217_1447"),
        ("papers", "0023_auto_20201221_1523"),
    ]

    operations = []
