# Generated by Django 3.1.1 on 2021-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0024_merge_20210224_1301")]

    operations = [
        migrations.AlterField(
            model_name="amendment",
            name="state",
            field=models.CharField(
                choices=[
                    (
                        "draft",
                        '<u title="ⓘ This paper is a private draft and not ready for amendments.">Draft</u>',
                    ),
                    (
                        "public",
                        '<u title="ⓘ This paper is public and ready for amendments.">Published</u>',
                    ),
                    (
                        "final",
                        '<u title="ⓘ This paper is final no more changes can be made.">Finalized</u>',
                    ),
                ],
                max_length=12,
                verbose_name="state",
            ),
        )
    ]
