# Generated by Django 3.1.1 on 2021-03-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0025_auto_20210224_1504"),
        ("papers", "0026_auto_20210303_1348"),
    ]

    operations = []
