# Generated by Django 3.1.1 on 2021-03-31 11:57

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0028_auto_20210316_1445")]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("reject", "reject"),
                            ("accept", "accept"),
                            ("modified", "modified"),
                        ],
                        max_length=80,
                    ),
                ),
                ("reason", ckeditor.fields.RichTextField(blank=True)),
                (
                    "alternative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommended_by",
                        to="papers.amendment",
                        verbose_name="alternative",
                    ),
                ),
                (
                    "amendment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="papers.amendment",
                        verbose_name="Antrag",
                    ),
                ),
            ],
        )
    ]
