# Generated by Django 3.1.1 on 2021-03-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0029_recommendation"),
        ("papers", "0029_auto_20210331_1314"),
    ]

    operations = []
