# Generated by Django 3.1.1 on 2021-05-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("papers", "0030_merge_20210331_1327")]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="state",
            field=models.CharField(
                choices=[
                    (
                        "draft",
                        '<u title="ⓘ This paper is a private draft and not ready for amendments.">Draft</u>',
                    ),
                    (
                        "public",
                        '<u title="ⓘ This paper is public and ready for amendments.">Published</u>',
                    ),
                    (
                        "final",
                        '<u title="ⓘ This paper is final no more changes can be made.">Finalized</u>',
                    ),
                ],
                default="draft",
                max_length=20,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="amendment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="papers.amendment",
                verbose_name="amendment",
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="body")),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "amendment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="papers.amendment",
                        verbose_name="amendment",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="papers.author",
                        verbose_name="author",
                    ),
                ),
            ],
        ),
    ]
