# Generated by Django 3.1.8 on 2021-06-02 08:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0031_auto_20210507_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendment',
            options={'ordering': ['start_index'], 'verbose_name': 'Antrag', 'verbose_name_plural': 'Anträge'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor*in', 'verbose_name_plural': 'Autor*innen'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Kommentar', 'verbose_name_plural': 'Kommentare'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': 'Papier', 'verbose_name_plural': 'Papiere'},
        ),
        migrations.AlterModelOptions(
            name='papercomment',
            options={'verbose_name': 'Kommentar', 'verbose_name_plural': 'Kommentare'},
        ),
        migrations.AlterModelOptions(
            name='papertranslation',
            options={'verbose_name': 'Übersetzung aktualisieren', 'verbose_name_plural': 'Übersetzungen'},
        ),
        migrations.AlterField(
            model_name='amendment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.author', verbose_name='Autor*in'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='content',
            field=models.TextField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='end_index',
            field=models.IntegerField(default=0, verbose_name='Endindex'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='language_code',
            field=models.CharField(choices=[('de', 'German'), ('fr', 'French'), ('it', 'Italian')], max_length=7, verbose_name='Sprachcode'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper', verbose_name='Papier'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='reason',
            field=ckeditor.fields.RichTextField(verbose_name='Begründung'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='start_index',
            field=models.IntegerField(default=0, verbose_name='Startindex'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='state',
            field=models.CharField(choices=[('draft', '<u title="ⓘ This amendment is a draft.">Draft</u>'), ('public', '<u title="ⓘ This amendment is public.">Published</u>'), ('retracted', '<u title="ⓘ This amendment is retracted.">Retracted</u>'), ('accepted', '<u title="ⓘ This amendment is accepted.">Accepted</u>'), ('rejected', '<u title="ⓘ This amendment is rejected.">Rejected</u>')], max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='translations',
            field=models.ManyToManyField(related_name='_amendment_translations_+', to='papers.Amendment', verbose_name='Übersetzungen'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer*in'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='amendment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='papers.amendment', verbose_name='Antrag'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.author', verbose_name='Autor*in'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='note',
            name='amendment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='papers.amendment', verbose_name='Antrag'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.author', verbose_name='Autor*in'),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='amendment_deadline',
            field=models.DateTimeField(verbose_name='Antragsfrist'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, to='papers.Author', verbose_name='Autor*innen'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Bearbeitet am'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='state',
            field=models.CharField(choices=[('draft', '<u title="ⓘ This paper is a private draft and not ready for amendments.">Draft</u>'), ('public', '<u title="ⓘ This paper is public and ready for amendments.">Published</u>'), ('final', '<u title="ⓘ This paper is final no more changes can be made.">Finalized</u>')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='working_title',
            field=models.CharField(max_length=255, verbose_name='Working title'),
        ),
        migrations.AlterField(
            model_name='papercomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.author', verbose_name='Autor*in'),
        ),
        migrations.AlterField(
            model_name='papercomment',
            name='body',
            field=models.TextField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='papercomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='papercomment',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='papercomment',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='papers.paper', verbose_name='Papier'),
        ),
        migrations.AlterField(
            model_name='papertranslation',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='papertranslation',
            name='language_code',
            field=models.CharField(choices=[('de', 'German'), ('fr', 'French'), ('it', 'Italian')], max_length=7, verbose_name='Sprachcode'),
        ),
        migrations.AlterField(
            model_name='papertranslation',
            name='needs_update',
            field=models.BooleanField(default=False, help_text='Müssen die anderen Übersetzungen ebenfalls überarbeitet werden?'),
        ),
        migrations.AlterField(
            model_name='papertranslation',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_set', to='papers.paper', verbose_name='Papier'),
        ),
        migrations.AlterField(
            model_name='papertranslation',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by', to='papers.amendment', verbose_name='Alternative'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='amendment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='papers.amendment', verbose_name='Antrag'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation',
            field=models.CharField(choices=[('reject', 'ablehnen'), ('accept', 'annehmen'), ('modified', 'modifiziert annehmen')], max_length=80),
        ),
    ]
