# This file is a template, and might need editing before it works on your project.
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

black:
  stage: .pre
  script:
    - docker run -v $(pwd):/data -w /data milansuk/python-black black --check .

isort:
  stage: .pre
  script:
    - docker run -v $(pwd):/data -w /data python /bin/bash -c "pip install isort; isort ."

pylint:
  stage: .pre
  script:
    - docker run -v $(pwd):/data -w /data python /bin/bash -c "pip install pylint pylint-django; pip install -r requirements.txt; pylint --load-plugins pylint_django papers backend"
  allow_failure: true

django-test-master:
  stage: test
  script:
    - docker run "$CI_REGISTRY_IMAGE" python manage.py test
  only:
    - master

django-test:
  stage: test
  script:
    - docker run "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" python manage.py test
  except:
    - master

bandit:
  stage: pre
  script:
    - docker run -v $(pwd):/data -w /data python /bin/bash -c "pip install bandit; bandit -r ."
