version: '3.7'

services:
  web:
    build: .
    command: gunicorn -w 4 -k uvicorn.workers.UvicornH11Worker backend.asgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
  nginx:
    image: sacovo/nginx-pagespeed
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
      - ${PWD}/nginx.conf:/usr/local/nginx/conf/nginx.conf
    restart: always
    networks:
      - web
      - default
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  web:
    external: true

