version: '3.7'

services:
  web:
    image: cr.gitlab.fhnw.ch/ip34-20vt/ip34-20vt_digital-democracy/backend
    command: gunicorn -w 4 -k uvicorn.workers.UvicornH11Worker backend.asgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
    env_file:
      - ./env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env
  cache:
    image: memcached:alpine
  nginx:
    image: sacovo/nginx-pagespeed
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
    restart: always
    networks:
      - web
      - default
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.rule=Host(`your-domain-here.com`)"
      - "traefik.http.routers.backend.tls.certresolver=certresolver"

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  web:
    external: true

